[build]
builder = "nixpacks"
buildCommand = """
cd backend/gateway && npm install &&
cd ../services && npm install &&
cd ../../frontend && npm install
"""

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
directory = "backend"
startCommand = "node scripts/startAllServices.cjs"

[[services]]
name = "frontend"
directory = "frontend"